preferred_provider: azure_openai

providers:
  openai:
    api_key_env: OPENAI_API_KEY
    api_endpoint_env: OPENAI_ENDPOINT
    model: text-embedding-3-small

  gemini:
    api_key_env: GEMINI_API_KEY
    model: gemini-embedding-exp-03-07

  azure_openai:
    api_key_env: 3b24b09ccd2f4225864d6051e7173873
    api_endpoint_env: https://qv3-homes.openai.azure.com/
    api_version_env: "2025-01-01-preview"  # Specific API version for embeddings
    model: text-embedding-3-small

  snowflake:
    api_key_env: SNOWFLAKE_PAT
    api_endpoint_env: SNOWFLAKE_ACCOUNT_URL
    api_version_env: "2024-10-01"
    model: snowflake-arctic-embed-m-v1.5